### ISSUE TITLE
3 digit validation codes

### ISSUE THREAD

**Issue by peterjc** [Korijn/flake8-self#1]
Both flake8 itself and all the other flake8 plugins I have used have three digit numbers, so why not here?

**Comment by Korijn** [comment]
I honestly never noticed! Do you have a suggestion for a better code? Feel free to open a PR.

**Comment by peterjc** [comment]
I think there is a flake8 pull request somewhere about better documenting this, I'll see if I can find it...

**Comment by peterjc** [comment]
OK, found it, phrased as a recommendation:

> Please Note: Your entry point does not need to be exactly 4 characters as of Flake8 3.0. Consider using an entry point with 3 letters followed by 3 numbers (i.e. ABC123 ).

http://flake8.pycqa.org/en/latest/plugin-development/registering-plugins.html#register-a-plugin

For background and a whole bunch of examples which all use 3 digit numbers, see https://gitlab.com/pycqa/flake8/issues/339

**Comment by Korijn** [comment]
Looks like the convention is to use the first letter, and for S the first 100 series is occupied, so `S201` perhaps looks good?

Alternatively, using three letters as well, we could go for `SLF001`. What is your preference?

**Comment by peterjc** [comment]
No no no for ``S201``. Single letter prefixes are bad - the point of the list I made in https://gitlab.com/pycqa/flake8/issues/339 was to show how many collisions there were already.

The current recommendation is three letters, three numbers, so ``SLF001`` would be perfect.

**Comment by Korijn** [comment]
Would you mind reviewing #2?
