### ISSUE TITLE
cls private access false positive

### ISSUE THREAD

**Issue by anxodio** [Korijn/flake8-self#3]
First of all, thank you for this plugin! :)

I found a possible false positive... with a code like:

```python
class Foo(object):
   _cls_private_thing = 'foo'

   @classmethod
   def class_fn(cls):
      print(cls._cls_private_thing) # SLF001 Private member access
```

It raises private member access error, but it is a legal access (inside the class).

IMHO, It should work with conventions like cls or mcs (metaclass)

**Comment by Korijn** [comment]
Detecting that the member is accessed from `cls` is straightforward. I think it should be easy to build into the plugin. I will have a look later!

There are more ways to fool this plugin though :) use any other name than `self` or `cls` is valid python but the plugin will not pick it up correctly. I am not aware of an easy method to fix that from the AST though...

**Comment by anxodio** [comment]
> Detecting that the member is accessed from cls is straightforward. I think it should be easy to build into the plugin. I will have a look later!

I think so! Probably will be just checking against more strings in `node.value`.

> There are more ways to fool this plugin though :) use any other name than self or cls is valid python but the plugin will not pick it up correctly. I am not aware of an easy method to fix that from the AST though...

I agree, will be better to inspect if it's the first parameter of an instance method, class method... but I think it's harder and probably kind of useless... because if we follow the linting rules and the standards, we will always use `self`, `cls` or (unlikely) `mcs`.

If there is some user with more necessities, an easy solution would be have a configuration parameter with a list of extra valid names :thinking:
